apiVersion: apps/v1
kind: Deployment # Changed from ReplicaSet to Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 2 # Added replicas
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379